"use client"

import { useState } from "react"

type Insight = {
  summary: string
  lowStock: { part: string; current: number; reorderLevel: number; unit: string; urgency: "high" | "medium" | "low"; reason: string }[]
  predictions: { part: string; predictedNeed: number; unit: string; timeframe: string; confidence: "high" | "medium" | "low"; basedOn: string }[]
  orderSuggestion: string
  efficiency: string
}

type InsightsData = {
  insights: Insight | null
  parts: { name: string; quantity: number; unit: string; reorderLevel: number; supplier: string | null; supplierEmail: string | null; costPrice: number | null }[]
  upcomingBookings: number
  reason?: string
}

const urgencyColour = { high: "#991b1b", medium: "#92400e", low: "#166534" }
const urgencyBg = { high: "#fee2e2", medium: "#fffbeb", low: "#f0fdf4" }
const confidenceLabel = { high: "High confidence", medium: "Medium confidence", low: "Low confidence" }

export default function InsightsView({ garageId }: { garageId: string }) {
  const [data, setData] = useState<InsightsData | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [printMode, setPrintMode] = useState(false)

  const load = async () => {
    setLoading(true); setError(null)
    try {
      const res = await fetch("/api/insights")
      const json = await res.json()
      if (res.status === 429) {
        setError(json.message || "You've already generated insights today. Come back tomorrow.")
        setLoading(false)
        return
      }
      if (!res.ok) throw new Error(json.error || "Failed to load")
      setData(json)
    } catch (e) {
      setError(String(e))
    }
    setLoading(false)
  }

  const handlePrint = () => {
    setPrintMode(true)
    setTimeout(() => { window.print(); setPrintMode(false) }, 100)
  }

  const handleEmail = () => {
    if (!data?.insights) return
    const { insights, parts } = data
    const lowStock = parts.filter(p => p.quantity <= p.reorderLevel)

    const subject = encodeURIComponent("Parts Order — Fyca Inventory Suggestion")
    const body = encodeURIComponent([
      `AI Order Suggestion`,
      ``,
      insights.orderSuggestion,
      ``,
      `LOW STOCK ITEMS:`,
      ...lowStock.map(p => `- ${p.name}: ${p.quantity} ${p.unit} in stock (reorder at ${p.reorderLevel})`),
      ``,
      `Generated by Fyca`,
    ].join("\n"))

    const supplierEmails = [...new Set(parts.filter(p => p.supplierEmail).map(p => p.supplierEmail))]
    const mailto = `mailto:${supplierEmails.join(",")}?subject=${subject}&body=${body}`
    window.location.href = mailto
  }

  if (!data) {
    return (
      <div style={{ textAlign: "center", padding: "60px 0" }}>
        <div style={{ background: "#f4f3ef", borderRadius: 16, padding: "40px 32px", maxWidth: 480, margin: "0 auto" }}>
          <p style={{ fontFamily: "var(--font-fraunces),'Fraunces',serif", fontWeight: 600, fontSize: "1.2rem", color: "#111110", marginBottom: 10 }}>
            AI Parts Predictions
          </p>
          <p style={{ color: "#6b6a66", fontSize: "0.9rem", marginBottom: 28, lineHeight: 1.6 }}>
            Claude analyses your upcoming bookings and current stock to predict what parts you'll need — and when to order.
          </p>
          {error && <p style={{ color: "#991b1b", fontSize: "0.875rem", marginBottom: 16 }}>{error}</p>}
          <button
            onClick={load}
            disabled={loading}
            style={{ background: "#111110", color: "#ffffff", padding: "12px 28px", borderRadius: 100, fontWeight: 600, fontSize: "0.9rem", border: "none", cursor: loading ? "not-allowed" : "pointer", opacity: loading ? 0.7 : 1 }}
          >
            {loading ? "Analysing…" : "Generate insights"}
          </button>
        </div>
      </div>
    )
  }

  if (data.reason === "no_parts") {
    return (
      <div style={{ background: "#f4f3ef", borderRadius: 14, padding: "48px", textAlign: "center" }}>
        <h3 style={{ fontFamily: "var(--font-fraunces),'Fraunces',serif", fontWeight: 600, fontSize: "1.1rem", color: "#111110", marginBottom: 8 }}>No parts to analyse</h3>
        <p style={{ color: "#6b6a66", fontSize: "0.9rem" }}>Add parts to your inventory first, then come back for AI predictions.</p>
      </div>
    )
  }

  const { insights, parts, upcomingBookings } = data
  if (!insights) return null

  return (
    <div className={printMode ? "print-mode" : ""}>
      {/* Header actions */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 28, flexWrap: "wrap", gap: 12 }}>
        <div>
          <p style={{ fontSize: "0.82rem", color: "#6b6a66" }}>
            Based on {upcomingBookings} upcoming booking{upcomingBookings !== 1 ? "s" : ""} and your current stock
          </p>
        </div>
        <div style={{ display: "flex", gap: 10 }}>
          <button onClick={load} disabled={loading} style={{ background: "transparent", color: "#111110", border: "0.5px solid rgba(0,0,0,0.2)", padding: "8px 16px", borderRadius: 100, fontWeight: 600, fontSize: "0.8rem", cursor: "pointer" }}>
            {loading ? "Refreshing…" : "Refresh"}
          </button>
          <button onClick={handleEmail} style={{ background: "transparent", color: "#111110", border: "0.5px solid rgba(0,0,0,0.2)", padding: "8px 16px", borderRadius: 100, fontWeight: 600, fontSize: "0.8rem", cursor: "pointer" }}>
            Email order
          </button>
          <button onClick={handlePrint} style={{ background: "#111110", color: "#ffffff", border: "none", padding: "8px 16px", borderRadius: 100, fontWeight: 600, fontSize: "0.8rem", cursor: "pointer" }}>
            Print order
          </button>
        </div>
      </div>

      {/* Summary */}
      <div style={{ background: "#111110", borderRadius: 14, padding: "22px 24px", marginBottom: 20 }}>
        <p style={{ fontSize: "0.72rem", fontWeight: 700, color: "rgba(255,255,255,0.4)", textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 8 }}>Summary</p>
        <p style={{ color: "#ffffff", fontSize: "0.95rem", lineHeight: 1.6, margin: 0 }}>{insights.summary}</p>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 20 }}>
        {/* Low stock */}
        <div style={{ background: "#f4f3ef", borderRadius: 14, padding: "20px 22px" }}>
          <p style={sectionTitle}>Low stock alerts</p>
          {insights.lowStock.length === 0 ? (
            <p style={{ fontSize: "0.875rem", color: "#6b6a66" }}>All parts are well stocked.</p>
          ) : (
            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              {insights.lowStock.map((item, i) => (
                <div key={i} style={{ background: "#ffffff", borderRadius: 10, padding: "12px 14px" }}>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 4 }}>
                    <span style={{ fontWeight: 600, fontSize: "0.875rem", color: "#111110" }}>{item.part}</span>
                    <span style={{ background: urgencyBg[item.urgency], color: urgencyColour[item.urgency], fontSize: "0.7rem", fontWeight: 700, padding: "2px 8px", borderRadius: 100 }}>
                      {item.urgency}
                    </span>
                  </div>
                  <p style={{ fontSize: "0.8rem", color: "#6b6a66", margin: "0 0 4px" }}>{item.current} {item.unit} left (reorder at {item.reorderLevel})</p>
                  <p style={{ fontSize: "0.8rem", color: "#444441", margin: 0 }}>{item.reason}</p>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Predictions */}
        <div style={{ background: "#f4f3ef", borderRadius: 14, padding: "20px 22px" }}>
          <p style={sectionTitle}>Predicted needs</p>
          {insights.predictions.length === 0 ? (
            <p style={{ fontSize: "0.875rem", color: "#6b6a66" }}>No predictions yet — add more booking history.</p>
          ) : (
            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              {insights.predictions.map((item, i) => (
                <div key={i} style={{ background: "#ffffff", borderRadius: 10, padding: "12px 14px" }}>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 4 }}>
                    <span style={{ fontWeight: 600, fontSize: "0.875rem", color: "#111110" }}>{item.part}</span>
                    <span style={{ fontSize: "0.72rem", color: "#6b6a66" }}>{confidenceLabel[item.confidence]}</span>
                  </div>
                  <p style={{ fontSize: "0.8rem", color: "#444441", margin: "0 0 4px" }}>
                    ~{item.predictedNeed} {item.unit} needed {item.timeframe}
                  </p>
                  <p style={{ fontSize: "0.78rem", color: "#6b6a66", margin: 0 }}>{item.basedOn}</p>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Order suggestion */}
      <div style={{ background: "#f4f3ef", borderRadius: 14, padding: "20px 22px", marginBottom: 16 }}>
        <p style={sectionTitle}>Order recommendation</p>
        <p style={{ fontSize: "0.875rem", color: "#444441", lineHeight: 1.6, margin: 0 }}>{insights.orderSuggestion}</p>
      </div>

      {/* Efficiency tip */}
      <div style={{ background: "#f4f3ef", borderRadius: 14, padding: "20px 22px" }}>
        <p style={sectionTitle}>Efficiency tip</p>
        <p style={{ fontSize: "0.875rem", color: "#444441", lineHeight: 1.6, margin: 0 }}>{insights.efficiency}</p>
      </div>
    </div>
  )
}

const sectionTitle: React.CSSProperties = {
  fontWeight: 700, fontSize: "0.82rem", color: "#111110",
  textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 14,
}
